services:
  - type: web
    name: yt-stream
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: API_URL
        value: https://yt-stream-5v2o.onrender.com
      - key: YOUTUBE_SESSION_SERVER
        value: http://127.0.0.1:4416/token   
